# Generated by Django 4.2.4 on 2023-08-18 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_auth_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auth_data',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
