# Generated by Django 4.2.4 on 2023-08-18 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_auth_code_user_auth_code_1_user_auth_code_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='auth_data',
            field=models.DateTimeField(null=True),
        ),
    ]
