# Generated by Django 4.2.4 on 2023-08-18 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_auth_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='access_user',
            field=models.BooleanField(default=True),
        ),
    ]
