# Generated by Django 4.2.4 on 2023-08-18 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_access_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='access_user',
        ),
    ]
