# Generated by Django 4.2.4 on 2023-08-18 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_user_access_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='auth_code_1',
            field=models.CharField(blank=True, default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='user',
            name='auth_code_2',
            field=models.CharField(blank=True, default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='user',
            name='auth_data',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
